Chesire/Nekome

app/build.gradle
app/proguard-rules.pro
core/build.gradle
core/proguard-rules.pro

Turn on Proguard for the release builds of app

chore: enable proguard

---

app/build.gradle
app/src/androidTest/java/com/chesire/nekome/TestApplication.kt
app/src/androidTest/java/com/chesire/nekome/flow/login/DetailsTests.kt
app/src/androidTest/java/com/chesire/nekome/harness/FakeUrlHandler.kt
app/src/androidTest/java/com/chesire/nekome/helpers/Actions.kt
app/src/androidTest/java/com/chesire/nekome/helpers/IntExtensions.kt
app/src/androidTest/java/com/chesire/nekome/injection/components/TestComponent.kt
app/src/androidTest/java/com/chesire/nekome/injection/modules/FakeUrlModule.kt
app/src/main/java/com/chesire/nekome/flow/login/details/DetailsFragment.kt
app/src/main/java/com/chesire/nekome/injection/components/AppComponent.kt
app/src/main/java/com/chesire/nekome/injection/modules/UrlModule.kt
app/src/main/res/layout/fragment_details.xml
core/build.gradle
core/src/main/java/com/chesire/nekome/core/extensions/TextViewExtensions.kt
core/src/main/java/com/chesire/nekome/core/url/CustomTabsUrl.kt
core/src/main/java/com/chesire/nekome/core/url/UrlHandler.kt
core/src/main/res/values/strings.xml

Change the login screen to have forgot password and the option to sign up. Unfortunately since they go to the Kitsu website it does mention downloading their app, but its better than a user not being able to sign in.

refactor: login screen

---

app-search/src/main/java/com/chesire/nekome/app/search/results/ResultsViewHolder.kt
app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesViewHolder.kt
app/src/main/java/com/chesire/nekome/flow/Activity.kt
app/src/main/java/com/chesire/nekome/flow/login/syncing/SyncingFragment.kt
core/src/main/res/drawable/ic_insert_photo.xml

Add placeholder and error images when loading images using Glide

feat: add glide placeholder and error

---

app-discover/build.gradle
app-search/build.gradle
app-search/src/test/java/com/chesire/nekome/app/search/SearchViewModelTests.kt
app-search/src/test/java/com/chesire/nekome/app/search/results/ResultsViewModelTests.kt
core/src/test/java/com/chesire/nekome/core/models/ImageModelTests.kt
core/src/test/java/com/chesire/nekome/core/models/SeriesModelTests.kt
series/src/test/java/com/chesire/nekome/series/SeriesRepositoryTests.kt

Add some missing unit tests in areas and create some new test files where they have previously been missed

test: increase coverage

---

app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesViewHolder.kt
app-series/src/main/res/layout/adapter_item_series.xml
core/src/main/res/values/strings.xml

Populate the series list a bit more so it doesn't look as empty, added the start and end dates for a
series, if a date is not known then ????-??-?? will be shown instead

feat: show the series start and end dates on the list

---

app-search/src/main/java/com/chesire/nekome/app/search/SearchFragment.kt
app-settings/src/main/java/com/chesire/nekome/app/settings/SettingsFragment.kt
app-settings/src/main/res/values/keys.xml
app-settings/src/main/res/xml/preferences.xml
core/src/main/res/values/strings.xml

Add a link from the settings page that will take the user to the projects GitHub page

feat: add link to GitHub

---

README.md

Add some initial information to the readme, currently missing image assets but will be fine for now

chore: create a readme

---

app/src/main/res/layout/fragment_details.xml
app/src/main/res/layout/fragment_syncing.xml
core/src/main/res/values/dimens.xml

Update the details screen by bringing the login button in, and adding more margin to the top of the image.
Update the syncing screen so that the progress bar sits below the body text so its a bit easier to see.

refactor: update login flow

---

build.gradle

Release notes: https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-3-70-released/

chore(deps): update kotlin to 1.3.70

---

app/src/main/java/com/chesire/nekome/flow/Activity.kt
core/src/main/res/values/strings.xml

If user is forced to log out because of an invalid auth/refresh token, show a snackbar to tell the
user an error occurred

feat: show error message when forced to log out

---

package.json

Update husky and conventional changelog to their latest versions

chore(deps): update husky and conventional changelog

---

app-series/build.gradle
app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesListFragment.kt
app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesListViewModel.kt
app-series/src/main/res/layout/fragment_series_list.xml
app-series/src/main/res/menu/menu_series_list.xml
app-series/src/test/java/com/chesire/nekome/app/series/list/SeriesListViewModelTests.kt
app/src/androidTest/java/com/chesire/nekome/flow/series/FilterTests.kt
app/src/androidTest/java/com/chesire/nekome/flow/series/SortTests.kt
app/src/main/res/layout/view_app_bar.xml
core/src/main/res/values/strings.xml
core/src/main/res/values/styles.xml

Add pull to refresh into the series list and an option to the menu bar to manually force series update.

feat: allow manual refresh of series

---

app-login/src/main/java/com/chesire/nekome/app/login/details/DetailsFragment.kt
app-login/src/main/java/com/chesire/nekome/app/login/syncing/SyncingFragment.kt
app-profile/src/main/java/com/chesire/nekome/app/profile/ProfileFragment.kt
app-search/src/main/java/com/chesire/nekome/app/search/SearchFragment.kt
app-search/src/main/java/com/chesire/nekome/app/search/results/ResultsFragment.kt
app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesListFragment.kt

Instead of inflating the binding in the onCreateView, assign the layout in the constructor and assign the binding in the onViewCreated. Tidies up the assigning of the binding

refactor: change viewbinding declarations

---

app-login/build.gradle
app-login/src/main/java/com/chesire/nekome/app/login/details/DetailsViewModel.kt
app-login/src/main/java/com/chesire/nekome/app/login/syncing/SyncingViewModel.kt
app-profile/build.gradle
app-profile/src/main/java/com/chesire/nekome/app/profile/ProfileViewModel.kt
app-search/build.gradle
app-series/build.gradle
app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesListViewModel.kt
app-timeline/build.gradle
app/build.gradle
app/src/main/java/com/chesire/nekome/Activity.kt
app/src/main/java/com/chesire/nekome/ActivityViewModel.kt
app/src/main/java/com/chesire/nekome/Avatar.kt
app/src/main/java/com/chesire/nekome/LogoutHandler.kt
app/src/main/java/com/chesire/nekome/services/RefreshAuthWorker.kt
app/src/main/java/com/chesire/nekome/services/RefreshSeriesWorker.kt

Update some classes with minor style changes, and do a minor refactor around the Activity avatar usage.

refactor: minor code and style changes

---

app/src/test/java/com/chesire/nekome/ActivityViewModelTests.kt
codecov.yml
features/login/src/test/java/com/chesire/nekome/app/login/details/DetailsViewModelTests.kt
libraries/account/build.gradle
libraries/account/src/test/java/com/chesire/nekome/account/UserRepositoryTests.kt
libraries/core/build.gradle
libraries/core/src/test/java/com/chesire/nekome/core/models/SeriesModelTests.kt
libraries/core/src/test/java/com/chesire/nekome/core/settings/ThemeTests.kt
libraries/database/build.gradle
libraries/database/src/androidTest/java/com/chesire/nekome/database/dao/UserDaoTests.kt
libraries/kitsu/build.gradle
libraries/kitsu/src/main/java/com/chesire/nekome/kitsu/interceptors/AuthRefreshInterceptor.kt
libraries/kitsu/src/test/java/com/chesire/nekome/kitsu/api/library/KitsuLibraryTests.kt
libraries/kitsu/src/test/java/com/chesire/nekome/kitsu/api/trending/KitsuTrendingTests.kt
libraries/kitsu/src/test/java/com/chesire/nekome/kitsu/interceptors/AuthInjectionInterceptorTests.kt
libraries/kitsu/src/test/java/com/chesire/nekome/kitsu/interceptors/AuthRefreshInterceptorTests.kt

Update the code coverage throughout the project where possible. Refactoring some tests where required to make their a bit clearer or remove the need to mock out models.

test: update code coverage

---

.github/dependabot.yml
.gitignore
.idea/codeStyles/Project.xml
app/src/main/java/com/chesire/nekome/Avatar.kt
build.gradle
features/discover/src/main/java/com/chesire/nekome/app/discover/trending/TrendingViewHolder.kt
features/login/src/main/java/com/chesire/nekome/app/login/syncing/SyncingFragment.kt
features/profile/src/main/java/com/chesire/nekome/app/profile/ProfileFragment.kt
features/search/src/main/java/com/chesire/nekome/app/search/results/ResultsViewHolder.kt
features/series/src/main/java/com/chesire/nekome/app/series/list/view/SeriesViewHolder.kt
package.json

refactor: minor code cleanup

---

app/build.gradle
build.gradle
features/discover/build.gradle
features/login/build.gradle
features/profile/build.gradle
features/search/build.gradle
features/series/build.gradle
features/settings/build.gradle
features/timeline/build.gradle
gradle/wrapper/gradle-wrapper.properties
libraries/account/build.gradle
libraries/core/build.gradle
libraries/database/build.gradle
libraries/kitsu/build.gradle
libraries/library/build.gradle
libraries/server/build.gradle
testing/build.gradle

Update the sdk used from 29 to 30

refactor: update target sdk

---

app/build.gradle
features/discover/build.gradle
features/login/build.gradle
features/profile/build.gradle
features/search/build.gradle
features/series/build.gradle
features/settings/build.gradle
features/timeline/build.gradle
libraries/account/build.gradle
libraries/core/build.gradle
libraries/database/build.gradle
libraries/encryption/build.gradle
libraries/kitsu/build.gradle
libraries/library/build.gradle
libraries/server/build.gradle
testing/build.gradle

Change to use the new `plugins` block for the Gradle files, just a bit of cleanup

chore: use new gradle plugins

---

libraries/encryption/build.gradle

Ad the custom lintrules to the encryption module as they missed previously

chore: add the custom lint rules to the encryption module

---

.idea/kotlinc.xml
app/build.gradle
features/discover/build.gradle
features/login/build.gradle
features/profile/build.gradle
features/search/build.gradle
features/series/build.gradle
features/settings/build.gradle
features/timeline/build.gradle
libraries/account/build.gradle
libraries/core/build.gradle
libraries/database/build.gradle
libraries/encryption/build.gradle
libraries/kitsu/build.gradle
libraries/library/build.gradle
libraries/server/auth/build.gradle
libraries/server/library/build.gradle
libraries/server/search/build.gradle
libraries/server/trending/build.gradle
libraries/server/user/build.gradle
testing/build.gradle

Go through the Gradle files and remove parts that are no longer required.

chore: cleanup redundant parts of gradle file

---

.github/workflows/pre-merge.yml
Dangerfile
app/build.gradle
build.gradle

Increase the amount of warnings that Lint reports for the application.

chore: increase linting verbosity

---

app/build.gradle
app/ext.gradle

Set the name from the current git tag, and set the name based on the current time and date. If we
want to swap the location where it is built from bitrise this will be required.

chore: set the version name and code programatically

---

app/build.gradle

Update version name and the version code to the latest

chore: update the version name to 1.4.2

---

app/build.gradle
fastlane/metadata/android/en-GB/changelogs/21091120.txt
fastlane/metadata/android/en-US/changelogs/21091120.txt

Bump the app version to 1.5.0, add changelogs for fastlane along with this.

chore: bump app version

---

app/build.gradle
fastlane/metadata/android/en-GB/changelogs/21091122.txt
fastlane/metadata/android/en-US/changelogs/21091122.txt

Increment app version, and add changelogs

chore: bump app version to 1.5.1

---

app/build.gradle

chore: update application version

---

app/src/main/AndroidManifest.xml
build.gradle

Update to the latest supported so we can take the latest androidx dependencies

chore: update to sdk version 31

---

app/build.gradle

chore: update version name and code

---

app/build.gradle

Update the app version to 1.6.0

chore: update app version to 1.6.0

---

build.gradle
libraries/core/src/main/java/com/chesire/nekome/core/extensions/ViewExtensions.kt
testing/src/main/java/com/chesire/nekome/testing/CoroutinesMainDispatcherRule.kt

Updates the build sdk to 33 and makes a few minor changes.

chore: update build sdk to 33

---

gradle.properties

Remove jetifier and test out using the configuration cache to improve the build times.

chore: improve build speeds

---

features/series/src/main/java/com/chesire/nekome/app/series/item/ui/ItemScreen.kt
features/settings/src/main/java/com/chesire/nekome/app/settings/config/ui/ConfigScreen.kt

Some screens on small phones were unusable, have added scrolling on these screens now.

fix: content missing on some screens

---

app/src/androidTest/java/com/chesire/nekome/helpers/creation/SearchDomain.kt
features/search/src/main/java/com/chesire/nekome/app/search/host/ui/DomainMapper.kt
features/search/src/main/java/com/chesire/nekome/app/search/host/ui/HostScreen.kt
features/search/src/main/java/com/chesire/nekome/app/search/host/ui/HostViewModel.kt
features/search/src/main/java/com/chesire/nekome/app/search/host/ui/UIState.kt
features/search/src/test/java/com/chesire/nekome/app/search/host/core/SearchSeriesUseCaseTest.kt
features/search/src/test/java/com/chesire/nekome/app/search/host/ui/DomainMapperTest.kt
features/search/src/test/java/com/chesire/nekome/app/search/host/ui/HostViewModelTest.kt
features/series/src/main/java/com/chesire/nekome/app/series/collection/ui/DomainMapper.kt
libraries/datasource/search/src/main/java/com/chesire/nekome/datasource/search/SearchDomain.kt
libraries/kitsu/search/src/main/java/com/chesire/nekome/kitsu/search/KitsuSearchService.kt
libraries/kitsu/search/src/main/java/com/chesire/nekome/kitsu/search/SearchItemDtoMapper.kt
libraries/kitsu/search/src/main/java/com/chesire/nekome/kitsu/search/dto/SearchItemDto.kt
libraries/kitsu/search/src/test/java/com/chesire/nekome/kitsu/search/SearchCreation.kt
libraries/kitsu/search/src/test/java/com/chesire/nekome/kitsu/search/SearchItemDtoMapperTests.kt

Use the image quality and title settings for the search screen as well

fix: use new user settings for search

---

.idea/kotlinc.xml
core/compose/src/main/java/com/chesire/nekome/core/compose/ModifierExtensions.kt
core/resources/src/main/res/values-ja/strings.xml
core/resources/src/main/res/values/strings.xml
features/series/src/main/java/com/chesire/nekome/app/series/collection/ui/CollectionScreen.kt
features/series/src/main/java/com/chesire/nekome/app/series/item/core/GetImageUseCase.kt
features/series/src/main/java/com/chesire/nekome/app/series/item/ui/ItemScreen.kt
features/series/src/main/java/com/chesire/nekome/app/series/item/ui/ItemViewModel.kt
features/series/src/main/java/com/chesire/nekome/app/series/item/ui/UIState.kt
features/series/src/test/java/com/chesire/nekome/app/series/item/core/GetImageUseCaseTest.kt
features/series/src/test/java/com/chesire/nekome/app/series/item/ui/ItemViewModelTest.kt

Update the view that is shown when tapping on an item in the collection view.
This just makes it look a bit nicer and will be in a format thats better to extend in the future.

refactor: update series detail view

---

app/build.gradle
core/compose/build.gradle
core/preferences/build.gradle
features/login/build.gradle
features/search/build.gradle
features/series/build.gradle
features/settings/build.gradle
libraries/core/build.gradle
libraries/kitsu/build.gradle

Remove all usages of KAPT and instead use KSP.

chore: update all instances of kapt to use ksp

---

README.md

Improve the visibility of screenshots on readme

chore: reduce width of the screenshots for better visibility

---

features/settings/src/main/java/com/chesire/nekome/app/settings/config/ui/ConfigScreen.kt

Update to a more friendly person image if the avatar image isn't available.
Closes #1085

refactor: update the missing profile image icon

---

app/build.gradle.kts
fastlane/metadata/android/en-GB/changelogs/24010720.txt
fastlane/metadata/android/en-US/changelogs/24010720.txt

Update version and changelog for new release

chore: update version and changelog

---

.github/workflows/master.yml
.github/workflows/pre-merge.yml
.idea/kotlinc.xml
Dangerfile
build.gradle.kts

Add caching when building off master, and use the caches in the ci file.

ci: add caching
