Chesire/Nekome

database/src/main/java/com/chesire/nekome/database/RoomDB.kt

Update the database name to be nekome, and allow a custom name to be passed in if desired

fix: database name was still using malime

---

app-search/src/main/java/com/chesire/nekome/app/search/results/ResultsAdapter.kt
app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesAdapter.kt
app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesViewHolder.kt

Instead of binding the listeners to the view whenever the data changes, it should be more efficient to just bind the listeners when the view is first created instead.

refactor: bind listeners when creating viewholder

---

app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesViewHolder.kt
app-series/src/main/res/layout/adapter_item_series.xml
core/src/main/res/values/styles.xml

The list title and subtitle were too close together, changed the layout of the series item to hopefully account for that. Will also now work better with larger fonts and display sizes set.

fix: list titles too close

---

app-settings/proguard-rules.pro
app-settings/src/main/java/com/chesire/nekome/app/settings/oss/OssFragment.kt
core/proguard-rules.pro

ProGuard was stripping the licences out, it looks like even with the exclude for ProGuard it was having issues finding which libraries were being used, so switched to manually adding them

fix: licenses missing

---

app-series/src/main/res/layout/fragment_series_detail.xml

The bottom sheet colours are not defined in the application, it seems to be taking them from the
material design library. Change to set the theme on the bottom sheet layout so it always uses the
application theme as expected

fix: bottom sheet theme is incorrect

---

Gemfile.lock

Update the version of bundler that builds the Gemfile.lock, update a danger item along with it

chore: update bundler version to 2.1.2

---

app-discover/src/main/java/com/chesire/nekome/app/discover/DiscoverFragment.kt
app-profile/build.gradle
app-profile/src/main/java/com/chesire/nekome/app/profile/ProfileFragment.kt
app-search/src/main/java/com/chesire/nekome/app/search/SearchFragment.kt
app-search/src/main/java/com/chesire/nekome/app/search/results/ResultsFragment.kt
app-series/build.gradle
app-series/src/main/java/com/chesire/nekome/app/series/detail/SeriesDetailSheetFragment.kt
app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesListFragment.kt
app/src/main/java/com/chesire/nekome/flow/Activity.kt
app/src/main/java/com/chesire/nekome/flow/login/details/DetailsFragment.kt
app/src/main/java/com/chesire/nekome/flow/login/syncing/SyncingFragment.kt

Change how viewmodels are acquired in fragments to use the `by viewModels { }` syntax

refactor: use by viewmodels

---

account/build.gradle
account/src/main/java/com/chesire/nekome/account/UserRepository.kt
account/src/test/java/com/chesire/nekome/account/UserRepositoryTests.kt
app-profile/build.gradle
app-profile/src/main/java/com/chesire/nekome/app/profile/ProfileViewModel.kt
app-profile/src/test/java/com/chesire/nekome/app/profile/ProfileViewModelTests.kt
app-search/build.gradle
app-search/src/main/java/com/chesire/nekome/app/search/results/ResultsViewModel.kt
app-search/src/test/java/com/chesire/nekome/app/search/results/ResultsViewModelTests.kt
app-series/build.gradle
app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesListViewModel.kt
app-series/src/test/java/com/chesire/nekome/app/series/list/SeriesListViewModelTests.kt
app/build.gradle
app/src/main/java/com/chesire/nekome/flow/ActivityViewModel.kt
app/src/main/java/com/chesire/nekome/flow/login/syncing/SyncingViewModel.kt
app/src/test/java/com/chesire/nekome/flow/login/syncing/SyncingViewModelTests.kt
database/src/main/java/com/chesire/nekome/database/dao/SeriesDao.kt
database/src/main/java/com/chesire/nekome/database/dao/UserDao.kt
series/build.gradle
series/src/main/java/com/chesire/nekome/series/SeriesRepository.kt
series/src/test/java/com/chesire/nekome/series/SeriesRepositoryTests.kt

It is recommended from various articles and from the Android dev summit (https://www.youtube.com/watch?v=B8ppnjGPAGE) that flow should be used for the non-ui layers.
Change moves from using LiveData in the Database and Repository to using Flow, and having just the ViewModel<->View using LiveData.
Further work will be done in the future to clean up the repository use.

refactor: change to use flow from database

---

account/build.gradle
app-discover/build.gradle
app-profile/build.gradle
app-search/build.gradle
app-series/build.gradle
app-settings/build.gradle
app-timeline/build.gradle
app/build.gradle
build.gradle
core/build.gradle
database/build.gradle
kitsu/build.gradle
series/build.gradle
server/build.gradle
testing/build.gradle

Add Chesire/LintRules to the project to give extra lint checks, it looks like some of them aren't
running in the app-* modules though strangely... the lexicographic ordering of Gradle dependencies
looks to have worked in app-timeline/build.gradle, but wasn't working in app-settings/build.gradle,
unsure why, the only thing I can think of is that one of them gets compiled into the main
application, the other does not currently. Unsure why this would have an effect though.

chore: add library to add linting rules to project

---

app-series/src/main/java/com/chesire/nekome/app/series/list/EmptyableRecyclerView.kt
app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesListFragment.kt
app-series/src/main/res/layout/fragment_series_list.xml
app-series/src/main/res/layout/view_empty.xml
core/src/main/java/com/chesire/nekome/core/extensions/ViewExtensions.kt
core/src/main/res/values/strings.xml

When the series list is empty there should be a different UI to show the user that there are no series under that current filter.

feat: add empty series list view

---

app/src/androidTest/java/com/chesire/nekome/flow/series/FilterTests.kt
app/src/androidTest/java/com/chesire/nekome/flow/series/SeriesListTests.kt
app/src/androidTest/java/com/chesire/nekome/flow/series/SeriesViewHolderTests.kt
app/src/androidTest/java/com/chesire/nekome/flow/series/SortTests.kt
app/src/androidTest/java/com/chesire/nekome/helpers/AuthProviderExtensions.kt
app/src/androidTest/java/com/chesire/nekome/injection/components/TestComponent.kt

Add some missing ui tests to hit some parts of the series module, this should now hit the view holder parts for the series list, and also the dialogs.
Will still need to write some tests to ensure that the filter/sort works correctly on the list itself, currently the tests just ensure the dialogs are working as intended.

test: update ui tests interacting with the series module

---

app-search/src/main/java/com/chesire/nekome/app/search/SearchFragment.kt
app-search/src/main/java/com/chesire/nekome/app/search/SearchPreferences.kt
app-search/src/test/java/com/chesire/nekome/app/search/SearchPreferencesTests.kt

Set the Anime type when reaching the search screen. Once a choice has been commited it will save
this option in preferences for the next time the user reaches this screen

feat: set an initial type when reaching the search screen

---

app-search/src/main/java/com/chesire/nekome/app/search/results/ResultsViewModel.kt
app-search/src/test/java/com/chesire/nekome/app/search/results/ResultsViewModelTests.kt
app-series/src/main/java/com/chesire/nekome/app/series/list/DialogHandler.kt
app-settings/src/main/java/com/chesire/nekome/app/settings/SettingsFragment.kt
app-settings/src/main/res/xml/preferences.xml
core/src/main/java/com/chesire/nekome/core/ApplicationSettings.kt
core/src/main/java/com/chesire/nekome/core/flags/UserSeriesStatus.kt
core/src/main/res/values/keys.xml
core/src/main/res/values/strings.xml
core/src/test/java/com/chesire/nekome/core/ApplicationSettingsTests.kt
core/src/test/java/com/chesire/nekome/core/flags/UserSeriesStatusTests.kt

Allow a user to choose what the default state will be when a user begins tracking a new series.
This introduces an ApplicationSettings class that will be the top level class to forward on any application settings to the rest of the application.

feat: allow choosing default new series state

---

app-search/src/main/java/com/chesire/nekome/app/search/SearchViewModel.kt
app-search/src/test/java/com/chesire/nekome/app/search/SearchViewModelTests.kt

To use the search api a valid auth token is required, so if that is invalid and the refresh token
did not work notify the authCaster to handle logging out

fix: notify the authcaster from search if could not refresh token

---

app/src/androidTest/java/com/chesire/nekome/harness/FakeAuthApi.kt
app/src/main/java/com/chesire/nekome/App.kt
app/src/main/java/com/chesire/nekome/injection/components/AppComponent.kt
app/src/main/java/com/chesire/nekome/services/RefreshAuthWorker.kt
app/src/main/java/com/chesire/nekome/services/WorkerQueue.kt
app/src/test/java/com/chesire/nekome/services/RefreshAuthWorkerTests.kt
app/src/test/java/com/chesire/nekome/services/WorkerQueueTests.kt
kitsu/src/main/java/com/chesire/nekome/kitsu/api/auth/KitsuAuth.kt
kitsu/src/main/java/com/chesire/nekome/kitsu/interceptors/AuthRefreshInterceptor.kt
kitsu/src/test/java/com/chesire/nekome/kitsu/api/auth/KitsuAuthTests.kt
server/src/main/java/com/chesire/nekome/server/api/AuthApi.kt

The auth token was not being refreshed by the background worker, so if a user did not update any series within the time for the tokens to expire (I think 30days?) then it would no longer work.
This was failing due to an assumption that getting the user details with a filter of `self` would require a user to be logged in, but it did not, so instead a new worker was added that will go out and refresh the auth token every 7 days to ensure it remains valid.

fix: auth token not refreshing

---

account/build.gradle
app-discover/build.gradle
app-profile/build.gradle
app-search/build.gradle
app-series/build.gradle
app-settings/build.gradle
app-timeline/build.gradle
app/build.gradle
build.gradle
core/build.gradle
database/build.gradle
jacoco.gradle
kitsu/build.gradle
series/build.gradle
server/build.gradle
testing/build.gradle

Cleanup the Gradle files to be more consistent across the board, removing the versionName/versionCode where it wasn't required, and making the files more in line with how the Kotlin DSL would want them to be, so it's easier to change in the future.

chore: cleanup gradle files

---

app/src/main/res/layout/fragment_details.xml

The progress spinner was touching the top and bottom of the button it was housed in, this didn't
look great. Refactor the control to use a constraintlayout so we can centre the progress spinner
into the middle of the button

refactor: shrink the progress spinner in the login screen

---

app/src/main/java/com/chesire/nekome/flow/Activity.kt
app/src/main/java/com/chesire/nekome/flow/login/details/DetailsFragment.kt

Ensure that the login details are stored through configuration change by using `onSaveInstanceState`, from what i've read the text should have been stored by using IDs on the view elements, but it doesn't look like it was working in this instance.

fix: restore details state on config change

---

app/src/main/java/com/chesire/nekome/flow/login/details/DetailsFragment.kt

Details doesn't need to use savedInstanceState because it is using ids which means Android will
store the username and password on configuration change anyway. Looks like it was failing before due
to the view being recreated, so the onSavedInstanceState was useless

refactor: remove savedinstancestate for the details view

---

app-series/src/main/java/com/chesire/nekome/app/series/detail/SeriesDetailViewModel.kt
app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesListFragment.kt

Clean up a memory leak around the series detail fragment, the bottom sheet dialog instance was being leaked. Looks like retaining the instance / using a `childFragmentManager` as opposed to the `parentFragmentManager` was causing it to be leaked.
This solves one of the leaks, there are still two more that need to be investigated.
Fixes part of #123

fix: cleanup memory leaks

---

core/build.gradle

This reverts commit 4e19fc94daf79e5c722531b4238ed01d60cc910a.
The consumerProguardRules were needed for anything consuming the core library
to ensure the proguard rules were set up correctly. Without this proguard file
the application will crash when trying to perform various operations.

revert: chore: remove unused proguard line

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
kitsu/src/main/java/com/chesire/nekome/kitsu/ResponseParsing.kt
kitsu/src/main/java/com/chesire/nekome/kitsu/api/auth/KitsuAuth.kt
kitsu/src/test/java/com/chesire/nekome/kitsu/ResponseParsingTests.kt

Trying to login to account after proguard had run on the application was constantly failing.
It looks like this was an issue with R8 being quite aggressive, it will be fixed in a later version of R8 pushed with the Gradle plugin. For now force the version of R8 to be a later one with the fix.

fix: login failing after proguard has run

---

app-series/src/main/java/com/chesire/nekome/app/series/list/SeriesListFragment.kt

Remove the field for the adapter since it isn't needed across the class, its only needed in the
livedata callbacks from the viewmodel which are setup in the onViewCreated anyway, this removes the
memory leak that was occurring in the series list
fixes #123

fix: remove memory leak due to leaking view

---

app-search/src/main/java/com/chesire/nekome/app/search/SearchFragment.kt
app-search/src/main/java/com/chesire/nekome/app/search/SearchPreferences.kt
app-search/src/main/res/layout/fragment_search.xml
app-search/src/test/java/com/chesire/nekome/app/search/SearchPreferencesTests.kt
core/src/main/java/com/chesire/nekome/core/flags/SeriesType.kt
core/src/test/java/com/chesire/nekome/core/flags/SeriesTypeTests.kt

Search was not auto selecting which series type to use, this was because the value being stored was the ID of the control, which isn't reliable to use. Change this to use a field that is stored within the SeriesType enum, so we can reference back to that.
As part of this also fix the user being able to unselect which chip was selected.

fix: search not auto selecting type

---

codecov.yml

The injection code shouldn't be covered by code coverage, it was still pointing to a directory for
the old application Malime, needs to be updated to point to the new application Nekome

chore: skip coverage for injection code

---

app-series/src/main/java/com/chesire/nekome/app/series/list/view/SeriesViewHolder.kt
app/src/androidTest/java/com/chesire/nekome/flow/series/SeriesViewHolderTests.kt
core/src/main/res/values/strings.xml

When the dates are unknown for the series list. Change the text so it instead shows "UNKNOWN", if
neither the start or end date are valid. And says "ONGOING" if just the end date is not known.
Closes #175

refactor: change series list text when dates are unknown

---

app/src/main/java/com/chesire/nekome/binders/UserProviderBinder.kt
app/src/main/java/com/chesire/nekome/injection/modules/SeriesModule.kt
app/src/test/java/com/chesire/nekome/binders/UserProviderBinderTests.kt
series/build.gradle
series/src/main/java/com/chesire/nekome/series/SeriesRepository.kt
series/src/main/java/com/chesire/nekome/series/UserProvider.kt
series/src/test/java/com/chesire/nekome/series/SeriesRepositoryTests.kt

Within the SeriesRepository was a reference to the UserRepository, this shouldn't occur. To fix this create an interface and pass an object implementing it into the SeriesRepository.

refactor: remove user repository from series

---

.github/dependabot.yml

Ensure that the github actions versions are alll updated to their latest versions

chore: add github actions to dependabot

---

gradle/wrapper/gradle-wrapper.properties

Gradle wrapper was not using the recommended settings, it was using -bin instead of -all

chore: update gradle wrapper to use -all

---

app/src/main/java/com/chesire/nekome/Activity.kt
features/discover/src/main/java/com/chesire/nekome/app/discover/DiscoverFragment.kt
features/login/src/main/java/com/chesire/nekome/app/login/details/DetailsFragment.kt
features/login/src/main/java/com/chesire/nekome/app/login/syncing/SyncingFragment.kt
features/profile/src/main/java/com/chesire/nekome/app/profile/ProfileFragment.kt
features/search/src/main/java/com/chesire/nekome/app/search/SearchFragment.kt
features/search/src/main/java/com/chesire/nekome/app/search/results/ResultsFragment.kt
features/series/src/main/java/com/chesire/nekome/app/series/detail/SeriesDetailSheetFragment.kt
features/series/src/main/java/com/chesire/nekome/app/series/list/SeriesListFragment.kt

Instead of having to do `observe(viewLifecycleOwner, Observer {...)` switch to using the Kotlin SAM
so we can instead do `observe(viewLifecycleOwner) {...` to make it a bit cleaner

style: switch from using Observer to using Kotlin SAM

---

.github/workflows/android.yml

Using pull_request_target should allow forks to still run the Danger step
it was added to allow using secret env variables in situations such as
these.

ci: change from using pull_request to pull_request_target

---

app/src/main/java/com/chesire/nekome/Activity.kt
app/src/main/res/navigation/nav_graph.xml
features/settings/src/main/java/com/chesire/nekome/app/settings/SettingsFragment.kt
features/settings/src/main/res/xml/preferences.xml
libraries/core/src/main/java/com/chesire/nekome/core/flags/HomeScreenOptions.kt
libraries/core/src/main/java/com/chesire/nekome/core/settings/ApplicationSettings.kt
libraries/core/src/main/res/values/keys.xml
libraries/core/src/main/res/values/strings.xml
libraries/core/src/test/java/com/chesire/nekome/core/flags/HomeScreenOptionsTests.kt
libraries/core/src/test/java/com/chesire/nekome/core/settings/ApplicationSettingsTests.kt

- Updates navigation graph to have a global navigation option for manga similar to anime
- Adds an additional configuration for switching between anime/manga as similar to `UserSeriesStatus`
- Creates a preference to store the value of default home option and related string resources
- Adds logic to choose between navigating to anime or manga based on the stored option
Fixes #93

feat: adds default home screen option

---

gradle/wrapper/gradle-wrapper.properties

Instead of using the -bin option for gradle, switch to the -all option which is recommended

chore: update the gradle wrapper to use the -all version

---

features/series/build.gradle

Dependency isn't used, as we only use the Core material dialog in actuality

chore: remove the material dialog inputs dependency

---

features/series/src/main/res/raw/keep.xml

When running R8 over the project during build, it removes some of the MaterialDialog resource files,
causing a crash when attempting to open them. Add a `keep` file that will keep those resources

fix: r8 removing material dialog files

---

.idea/codeStyles/Project.xml
app/build.gradle
build.gradle
dependencies.gradle
detekt.gradle
ext.gradle
jacoco.gradle

Move some of the code from the projects build.gradle file out into different gradle files, making it a bit cleaner and more to the point

chore: cleanup the project build.gradle

---

.github/workflows/master.yml
.github/workflows/pre_merge.yml

Instead of just 'android' which ran everything on master and for all PRs, split up the files based
on if they are building master or a pull request. This cleans it up a little bit and makes it
slightly easier to update in the future

ci: split up the android ci file into multiple

---

features/settings/build.gradle

We already added the ktx dependency, so adding the default one without is not required and instead
produces a lint warning

chore: remove preferences dependency that wasn't using ktx

---

app/src/debug/AndroidManifest.xml

Manifest was only trying to provide the external storage permission, but this is unable to be used
when we are targeting android 10+, so remove the manifest completely

chore: remove debug manifest that was unused

---

app/build.gradle
build.gradle
features/discover/build.gradle
features/login/build.gradle
features/profile/build.gradle
features/search/build.gradle
features/series/build.gradle
features/settings/build.gradle
features/timeline/build.gradle
libraries/account/build.gradle
libraries/core/build.gradle
libraries/database/build.gradle
libraries/kitsu/auth/build.gradle
libraries/kitsu/build.gradle
libraries/kitsu/library/build.gradle
libraries/kitsu/search/build.gradle
libraries/kitsu/trending/build.gradle
libraries/kitsu/user/build.gradle
libraries/library/build.gradle
testing/build.gradle

All usages of junit and mockk are hard coded into each of the gradle files, change them all to
instead use a variable from the project build.gradle

chore: make all test dependencies share dependency versions

---

features/search/src/test/java/com/chesire/nekome/app/search/SearchDomainMapperTests.kt
features/search/src/test/java/com/chesire/nekome/app/search/SearchViewModelTests.kt
libraries/kitsu/auth/src/main/java/com/chesire/nekome/kitsu/auth/dto/AuthResponseDto.kt
libraries/kitsu/auth/src/test/java/com/chesire/nekome/kitsu/auth/KitsuAuthTests.kt
libraries/kitsu/library/src/main/java/com/chesire/nekome/kitsu/library/dto/DataDto.kt
libraries/kitsu/library/src/test/java/com/chesire/nekome/kitsu/library/LibraryCreation.kt
libraries/kitsu/search/src/main/java/com/chesire/nekome/kitsu/search/SearchItemDtoMapper.kt
libraries/kitsu/search/src/main/java/com/chesire/nekome/kitsu/search/dto/SearchResponseDto.kt
libraries/kitsu/search/src/test/java/com/chesire/nekome/kitsu/search/KitsuSearchTests.kt
libraries/kitsu/search/src/test/java/com/chesire/nekome/kitsu/search/SearchItemDtoMapperTests.kt
libraries/kitsu/trending/src/main/java/com/chesire/nekome/kitsu/trending/TrendingItemDtoMapper.kt
libraries/kitsu/trending/src/test/java/com/chesire/nekome/kitsu/trending/TrendingItemDtoMapperTests.kt
libraries/kitsu/user/src/main/java/com/chesire/nekome/kitsu/user/KitsuUserService.kt
libraries/kitsu/user/src/main/java/com/chesire/nekome/kitsu/user/dto/UserItemDto.kt
libraries/kitsu/user/src/test/java/com/chesire/nekome/kitsu/user/KitsuUserTests.kt
libraries/kitsu/user/src/test/java/com/chesire/nekome/kitsu/user/UserItemDtoMapperTests.kt
libraries/server/search/src/main/java/com/chesire/nekome/search/api/SearchDomain.kt
libraries/server/trending/src/main/java/com/chesire/nekome/trending/api/TrendingDomain.kt

Throughout development several params have been added to the various DTO and Domain objects and have
just lived there. This removes a bunch of them, with more being removed in the future when it is
refactored to not use the SeriesModel everywhere.

refactor: remove various unused dto params

---

features/discover/src/main/java/com/chesire/nekome/app/discover/DiscoverViewModel.kt
features/discover/src/main/java/com/chesire/nekome/app/discover/domain/DiscoverDomainMapper.kt
features/discover/src/main/java/com/chesire/nekome/app/discover/domain/TrendingModel.kt
features/discover/src/main/java/com/chesire/nekome/app/discover/trending/TrendingAdapter.kt
features/discover/src/main/java/com/chesire/nekome/app/discover/trending/TrendingViewHolder.kt
libraries/kitsu/trending/src/main/java/com/chesire/nekome/kitsu/trending/TrendingItemDtoMapper.kt
libraries/kitsu/trending/src/main/java/com/chesire/nekome/kitsu/trending/dto/TrendingItemDto.kt
libraries/kitsu/trending/src/test/java/com/chesire/nekome/kitsu/trending/TrendingCreation.kt
libraries/kitsu/trending/src/test/java/com/chesire/nekome/kitsu/trending/TrendingItemDtoMapperTests.kt
libraries/server/trending/src/main/java/com/chesire/nekome/trending/api/TrendingDomain.kt

Remove usage of the SeriesModel from the Discover module, and reduce the amount of information pulled from the TrendingApi as it isn't required.

refactor: remove series model usage from trending

---

.idea/codeStyles/Project.xml
app/src/androidTest/java/com/chesire/nekome/flow/series/SeriesViewHolderTests.kt
app/src/androidTest/java/com/chesire/nekome/helpers/creation/LibraryDomain.kt
libraries/kitsu/library/src/main/java/com/chesire/nekome/kitsu/library/KitsuLibraryService.kt
libraries/kitsu/library/src/main/java/com/chesire/nekome/kitsu/library/ResponseDtoMapper.kt
libraries/kitsu/library/src/main/java/com/chesire/nekome/kitsu/library/dto/IncludedDto.kt
libraries/kitsu/library/src/test/java/com/chesire/nekome/kitsu/library/LibraryCreation.kt
libraries/library/src/test/java/com/chesire/nekome/library/LibraryDomainMapperTests.kt
libraries/library/src/test/java/com/chesire/nekome/library/SeriesRepositoryTests.kt
libraries/server/library/src/main/java/com/chesire/nekome/library/api/LibraryDomain.kt

When communicating with the series endpoints, more data was being pulled down than needed such as
the synopsis, this can be removed from the api calls to save on bandwidth and storage

refactor: remove various unused params from the series interaction

---

.github/workflows/pre-merge.yml

Remove pull_request_target due to security considerations, _target was only needed for forked
contributions and isn't worth the hassle instead of using pull_request

ci: update github actions to remove pull_request_target

---

libraries/kitsu/library/src/main/java/com/chesire/nekome/kitsu/library/KitsuLibrary.kt

KitsuLibrary was using reflection via a KSuspendFunction to invoke one of two methods passed in.
This could be changed to a lambda to have the same effect without needing to use reflection.
Closes #396

refactor: remove usage of reflection in the KitsuLibrary

---

features/series/src/main/java/com/chesire/nekome/app/series/list/SeriesListViewModel.kt
features/series/src/test/java/com/chesire/nekome/app/series/list/SeriesListViewModelTests.kt

In other parts of the application we are forcing the user to be logged out if the token is invalid,
but it was missed in the SeriesList, now if the user tries to refresh the series and their token is
invalid it will log them out.
Fixes #452

fix: force a user logout if the refresh token is invalid

---

detekt.yml
features/search/src/main/java/com/chesire/nekome/app/search/SearchViewModel.kt
features/search/src/main/java/com/chesire/nekome/app/search/results/ResultsViewModel.kt
features/search/src/test/java/com/chesire/nekome/app/search/SearchViewModelTests.kt
features/search/src/test/java/com/chesire/nekome/app/search/results/ResultsViewModelTests.kt
features/series/src/main/java/com/chesire/nekome/app/series/detail/SeriesDetailViewModel.kt
features/series/src/main/java/com/chesire/nekome/app/series/list/SeriesListViewModel.kt
features/series/src/test/java/com/chesire/nekome/app/series/detail/SeriesDetailViewModelTests.kt
features/series/src/test/java/com/chesire/nekome/app/series/list/SeriesListViewModelTests.kt
libraries/core/src/main/java/com/chesire/nekome/core/Resource.kt
libraries/kitsu/src/main/java/com/chesire/nekome/kitsu/AuthException.kt
libraries/kitsu/src/main/java/com/chesire/nekome/kitsu/ResponseParsing.kt
libraries/kitsu/src/main/java/com/chesire/nekome/kitsu/interceptors/AuthRefreshInterceptor.kt
libraries/kitsu/src/test/java/com/chesire/nekome/kitsu/interceptors/AuthRefreshInterceptorTests.kt
libraries/library/src/main/java/com/chesire/nekome/library/SeriesRepository.kt

Update the interceptor so when it attempts to update the auth token, if it fails it will now notify
the AuthCaster itself, instead of passing the error back down to the view models to handle

refactor: update interceptor to globally handle invalid auth

---

app/proguard-rules.pro

Some of the new domain classes were causing an issue at runtime because the navigation component was
trying to use them, but the obfuscation would cause it to fail. The documentation states to add them
to the proguard file, so go with that to fix them

fix: proguard causing runtime crash

---

libraries/database/build.gradle
libraries/database/src/test/java/com/chesire/nekome/database/MigrationTests.kt
libraries/database/src/test/java/com/chesire/nekome/database/dao/SeriesDaoTests.kt
libraries/database/src/test/java/com/chesire/nekome/database/dao/UserDaoTests.kt

Instead of running the tests using a real device/emulator, run them on the jvm using robolectric.
This should speed them up, and allow us to get code coverage for the database classes and migrations.
Closes #487

test: use robolectric to run the database tests

---

app/build.gradle
features/discover/build.gradle
features/login/build.gradle
features/profile/build.gradle
features/search/build.gradle
features/series/build.gradle
features/settings/build.gradle
libraries/account/build.gradle
libraries/core/build.gradle
libraries/kitsu/auth/build.gradle
libraries/kitsu/build.gradle
libraries/kitsu/library/build.gradle
libraries/kitsu/search/build.gradle
libraries/kitsu/trending/build.gradle
libraries/kitsu/user/build.gradle
libraries/library/build.gradle
libraries/server/auth/build.gradle
libraries/server/library/build.gradle
libraries/server/search/build.gradle
libraries/server/trending/build.gradle
libraries/server/user/build.gradle
testing/build.gradle

path: isn't needed when defining the project dependencies, so remove it

chore: remove the path part of project dependencies

---

.github/workflows/pre-merge.yml

Change from using a specific Github action to run Danger, and instead execute the commands manually.

ci: run danger manually

---

build.gradle

Since allopen is no longer used, it can be removed from the project.

chore: remove the all-open plugin as it isnt required anymore

---

app/build.gradle
build.gradle
features/discover/build.gradle
features/login/build.gradle
features/profile/build.gradle
features/search/build.gradle
features/series/build.gradle
features/settings/build.gradle
features/timeline/build.gradle
libraries/core/build.gradle
libraries/database/build.gradle
libraries/datasource/auth/build.gradle
libraries/kitsu/auth/build.gradle
libraries/kitsu/build.gradle

Remove some unused dependencies in some files, and cleanup the naming of the version params. Also
split up the lifecycle version so its split into livedata and viewmodel.

chore: cleanup dependency files a bit

---

build.gradle
libraries/core/src/main/java/com/chesire/nekome/core/extensions/SharedPreferenceExtensions.kt
libraries/datasource/auth/build.gradle
libraries/datasource/auth/src/main/AndroidManifest.xml
libraries/datasource/auth/src/main/java/com/chesire/nekome/datasource/auth/local/AuthProvider.kt
libraries/datasource/auth/src/main/java/com/chesire/nekome/datasource/auth/local/LocalAuth.kt
libraries/datasource/auth/src/main/java/com/chesire/nekome/datasource/auth/local/LocalAuthV1.kt
libraries/datasource/auth/src/main/java/com/chesire/nekome/datasource/auth/local/LocalAuthV2.kt
libraries/datasource/auth/src/main/java/com/chesire/nekome/datasource/auth/local/PreferenceProvider.kt
libraries/datasource/auth/src/test/java/com/chesire/nekome/datasource/auth/local/AuthProviderTests.kt
libraries/datasource/auth/src/test/java/com/chesire/nekome/datasource/auth/local/LocalAuthV1Tests.kt
libraries/datasource/auth/src/test/java/com/chesire/nekome/datasource/auth/local/LocalAuthV2Tests.kt
libraries/encryption/src/main/java/com/chesire/nekome/encryption/KeystoreEncryption.kt

Crash is sometimes occurring when using the encryption library due to something wrong with the KeyStore in Android.
Done some debugging and it seemed to always be causing an issue while a value was in the preferences, so move away from using the library and instead use the new encrypted shared preferences when possible.
Once this has been merged for a few weeks the encryption library can be tore out completely.

fix: crash in encryption library

---

app/src/main/AndroidManifest.xml

From version 2.6.0 of work manager the manifest needs to be changed or there are failures to run.
Previously the `tools:node="remove"` was being used as it was causing an issue with Hilt, this line
needed to be updated to the latest specified in
https://developer.android.com/jetpack/androidx/releases/work#2.6.0-alpha01.

fix: workmanager not being correctly initialized

---

app/build.gradle
app/src/main/java/com/chesire/nekome/injection/AppModule.kt
app/src/main/java/com/chesire/nekome/injection/FieldProvider.kt
build.gradle
features/settings/build.gradle
features/settings/consumer-rules.pro
features/settings/src/main/java/com/chesire/nekome/app/settings/oss/OssFragment.kt

Switch from using the Gradle dependency to get the definitions to instead use the plugin.
Closes #141

refactor: use the AboutLibraries plugin

---

app/build.gradle
features/profile/build.gradle
features/series/build.gradle
features/timeline/build.gradle
libraries/core/build.gradle
libraries/database/build.gradle

Remove some unused dependencies and copy the Room runtime dependency into app so we don't need to 
use api

chore: remove unused dependencies in gradle files

---

app/src/androidTest/java/com/chesire/nekome/features/series/SortTests.kt
app/src/androidTest/java/com/chesire/nekome/robots/series/SortOptionRobot.kt
features/series/src/main/java/com/chesire/nekome/app/series/list/view/SeriesAdapter.kt
libraries/core/src/main/java/com/chesire/nekome/core/flags/SortOption.kt
libraries/core/src/main/res/values/strings.xml
libraries/core/src/test/java/com/chesire/nekome/core/flags/SortOptionTests.kt

Small change to allow sorting by rating.
Would be nice to choose ascending/descending sort as well, but this was simple enough to do with no experience working on Android.
This was tested in the emulator in Android Studio.

Add ability to sort by rating

---

.idea/codeStyles/Project.xml
libraries/kitsu/library/src/main/java/com/chesire/nekome/kitsu/library/KitsuLibrary.kt
libraries/kitsu/library/src/main/java/com/chesire/nekome/kitsu/library/dto/RetrieveResponseDto.kt

If there was no items in a series list (such as anime), then the call to retrieve the series would
fail. Instead make it return an empty list but still a successful request. 
This fixes the issue of if a user has only anime in their library, or only manga.
Fix #746

fix: failure to get series if no items

---

.github/workflows/pre-merge.yml

Update the ruby action to use the non-deprecated one, and updated the version to 2.7

ci: update the ruby github action

---

gradle/libs.versions.toml
libraries/datasource/auth/src/main/java/com/chesire/nekome/datasource/auth/local/PreferenceProvider.kt

When creating the encrypted preferences, sometimes it will fail and crash. It looks like this could be an issue with the tink library that google makes use of which is updated in later dependency versions. Updating to the latest should hopefully fix it.

fix: issue with creating encrypted preferences

---

app/src/androidTest/java/com/chesire/nekome/features/ActivityTests.kt

Mistakenly was overwriting the `applicationPreferences` in the `ActivityTests` file, remove this so the tests can compile again.

test: fix the ui tests failing to compile

---

features/series/src/main/java/com/chesire/nekome/app/series/collection/ui/CollectionScreen.kt
features/series/src/main/java/com/chesire/nekome/app/series/collection/ui/CollectionViewModel.kt
features/series/src/main/java/com/chesire/nekome/app/series/collection/ui/UIState.kt

Add a flag to indicate if the screen is initalizing so we can wait until its initialized to show if there are no series found.

fix: stop the no series found text from showing on start

---

app/src/main/java/com/chesire/nekome/ui/MainActivity.kt
core/preferences/src/main/java/com/chesire/nekome/core/preferences/flags/Theme.kt
core/preferences/src/test/java/com/chesire/nekome/core/preferences/flags/ThemeTests.kt
core/resources/src/main/res/values-ja/strings.xml
core/resources/src/main/res/values/strings.xml

Add user settings for dynamic themes, and make use of them when loading the app.

fix: make use of the user setting for theme

---

.gitignore
core/compose/src/main/java/com/chesire/nekome/core/compose/ModifierExtensions.kt
features/login/src/main/java/com/chesire/nekome/app/login/credentials/ui/CredentialsScreen.kt
features/series/src/main/java/com/chesire/nekome/app/series/collection/ui/CollectionScreen.kt
features/series/src/main/java/com/chesire/nekome/app/series/collection/ui/RatingDialog.kt
features/settings/src/main/java/com/chesire/nekome/app/settings/config/ui/ConfigScreen.kt
libraries/datasource/auth/build.gradle
libraries/datasource/auth/src/main/java/com/chesire/nekome/datasource/auth/remote/AuthRefreshInterceptor.kt
libraries/datasource/auth/src/test/java/com/chesire/nekome/datasource/auth/remote/AuthRefreshInterceptorTests.kt

Fix various ui issues that arose from switching to compose.
Except 1410f07bb1b5a70f5f22bcad396edfd9a63fba40, this is something that has always been around that needed fixing.

fix: ui issues in compose

---

features/settings/src/main/java/com/chesire/nekome/app/settings/config/ui/ConfigViewModel.kt

If the user object has been remove somehow, then the user will crash every time they open the config view. Instead execute a log out for the user so they can then log back in.

fix: crash when user object is gone

---

app/src/androidTest/java/com/chesire/nekome/UITest.kt
app/src/androidTest/java/com/chesire/nekome/features/ActivityTests.kt
app/src/androidTest/java/com/chesire/nekome/features/login/CredentialsTests.kt
app/src/androidTest/java/com/chesire/nekome/features/login/LoginFlowTests.kt
app/src/androidTest/java/com/chesire/nekome/features/search/SearchTests.kt
app/src/androidTest/java/com/chesire/nekome/features/series/FilterTests.kt
app/src/androidTest/java/com/chesire/nekome/features/series/SeriesListTests.kt
app/src/androidTest/java/com/chesire/nekome/features/series/SortTests.kt
app/src/androidTest/java/com/chesire/nekome/features/settings/SettingsTests.kt
app/src/androidTest/java/com/chesire/nekome/injection/MockAuthModule.kt
app/src/androidTest/java/com/chesire/nekome/injection/MockLibraryModule.kt
app/src/androidTest/java/com/chesire/nekome/injection/MockSearchModule.kt
app/src/androidTest/java/com/chesire/nekome/injection/MockUserModule.kt
app/src/main/java/com/chesire/nekome/injection/DatabaseModule.kt
app/src/main/java/com/chesire/nekome/injection/ServerModule.kt
app/src/main/java/com/chesire/nekome/injection/TrendingModule.kt
app/src/main/java/com/chesire/nekome/injection/UserModule.kt
app/src/main/java/com/chesire/nekome/injection/WorkerModule.kt
gradle/libs.versions.toml

Remove the usage of `UninstallModules` in tests since it is bad performance, and instead use `TestInstallIn` for all of the APIs.

test: remove usage of uninstall modules

---

app/src/androidTest/java/com/chesire/nekome/features/settings/SettingsTests.kt
app/src/androidTest/java/com/chesire/nekome/robots/settings/ConfigRobot.kt
app/src/androidTest/java/com/chesire/nekome/robots/settings/ImageQualityRobot.kt
core/preferences/src/main/java/com/chesire/nekome/core/preferences/SeriesPreferences.kt
core/preferences/src/main/java/com/chesire/nekome/core/preferences/flags/ImageQuality.kt
core/preferences/src/test/java/com/chesire/nekome/core/preferences/flags/ImageQualityTests.kt
core/resources/src/main/res/values-ja/strings.xml
core/resources/src/main/res/values/strings.xml
features/series/src/main/java/com/chesire/nekome/app/series/collection/ui/DomainMapper.kt
features/series/src/test/java/com/chesire/nekome/app/series/collection/ui/DomainMapperTest.kt
features/settings/src/main/java/com/chesire/nekome/app/settings/config/core/RetrievePreferencesUseCase.kt
features/settings/src/main/java/com/chesire/nekome/app/settings/config/core/UpdateImageQualityUseCase.kt
features/settings/src/main/java/com/chesire/nekome/app/settings/config/ui/ConfigScreen.kt
features/settings/src/main/java/com/chesire/nekome/app/settings/config/ui/ConfigViewModel.kt
features/settings/src/main/java/com/chesire/nekome/app/settings/config/ui/UIState.kt
features/settings/src/main/java/com/chesire/nekome/app/settings/config/ui/ViewAction.kt
features/settings/src/test/java/com/chesire/nekome/app/settings/config/core/RetrievePreferencesUseCaseTest.kt
features/settings/src/test/java/com/chesire/nekome/app/settings/config/core/UpdateImageQualityUseCaseTest.kt
features/settings/src/test/java/com/chesire/nekome/app/settings/config/ui/ConfigViewModelTest.kt
libraries/core/src/main/java/com/chesire/nekome/core/models/ImageModel.kt
libraries/core/src/test/java/com/chesire/nekome/core/models/ImageModelTests.kt

Add an option to change the image quality for various images in the app.
By default we have been using a low quality image, but for higher quality displays "medium" or "high" will look much nicer.

feat: add option to change image quality

---

libraries/datasource/auth/src/main/java/com/chesire/nekome/datasource/auth/remote/AuthRefreshInterceptor.kt

Crash log:
```
Exception java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
at okhttp3.internal.connection.RealCall.enterNetworkInterceptorExchange (RealCall.java:410)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:410)
at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:133)
at com.chesire.nekome.datasource.auth.remote.AuthRefreshInterceptor.intercept (AuthRefreshInterceptor.java:88)
at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:133)
at com.chesire.nekome.datasource.auth.remote.AuthInjectionInterceptor.intercept (AuthInjectionInterceptor.java:32)
at …
```

fix: illegalStateException in AuthRefreshInterceptor

---

features/search/src/main/java/com/chesire/nekome/app/search/host/ui/HostScreen.kt
features/series/src/main/java/com/chesire/nekome/app/series/collection/ui/CollectionScreen.kt

- Fix the images not filling up the entire height of the cards
- Add behaviour to perform search when pressing done on the keyboard

feature: add a couple of UI improvements

---

app/build.gradle.kts
app/proguard-rules.pro
fastlane/metadata/android/en-GB/changelogs/23101020.txt
fastlane/metadata/android/en-US/changelogs/23101020.txt

R8 is causing failures for api calls, fix by adding the correct proguard settings.

fix: r8 release failure

---

app/build.gradle.kts
build.gradle.kts
features/login/build.gradle.kts
features/search/build.gradle.kts
features/series/build.gradle.kts
features/settings/build.gradle.kts
gradle/libs.versions.toml

This plugin hasn't been used since moving to compose navigation, and wasn't required anymore.
Closes #1163

chore: remove unusued navigation args plugin

---

app/build.gradle.kts
app/src/main/java/com/chesire/nekome/ui/Routes.kt
app/src/main/java/com/chesire/nekome/ui/Screen.kt
fastlane/metadata/android/en-GB/changelogs/24012317.txt
fastlane/metadata/android/en-US/changelogs/24012317.txt
features/series/src/main/java/com/chesire/nekome/app/series/collection/ui/CollectionScreen.kt
features/series/src/main/java/com/chesire/nekome/app/series/collection/ui/CollectionViewModel.kt
features/series/src/main/java/com/chesire/nekome/app/series/collection/ui/UIState.kt
features/series/src/test/java/com/chesire/nekome/app/series/collection/ui/CollectionViewModelTest.kt

Remove passing the series name through to the Item screen as it is never used. This stops the crash occurring as titles such as Fate/Stay night would cause an exception.
Fixes #1162

fix: crash when navigating to series with slash in name
